const KASB = "https://www.kasb.or.kr/front/board/cmtreadListB.do";

const sources = {
  ifrs15: "https://www.ifrs.org/issued-standards/list-of-standards/ifrs-15-revenue-from-contracts-with-customers/",
  ias1: "https://www.ifrs.org/issued-standards/list-of-standards/ias-1-presentation-of-financial-statements/",
  ias8: "https://www.ifrs.org/issued-standards/list-of-standards/ias-8-accounting-policies-changes-in-accounting-estimates-and-errors/",
  ias10: "https://www.ifrs.org/issued-standards/list-of-standards/ias-10-events-after-the-reporting-period/",
  ias16: "https://www.ifrs.org/issued-standards/list-of-standards/ias-16-property-plant-and-equipment/",
  ias21: "https://www.ifrs.org/issued-standards/list-of-standards/ias-21-the-effects-of-changes-in-foreign-exchange-rates/",
  ias32: "https://www.ifrs.org/issued-standards/list-of-standards/ias-32-financial-instruments-presentation/",
  ias37: "https://www.ifrs.org/issued-standards/list-of-standards/ias-37-provisions-contingent-liabilities-and-contingent-assets/",
  ifrs9: "https://www.ifrs.org/issued-standards/list-of-standards/ifrs-9-financial-instruments/",
  ifrs16: "https://www.ifrs.org/issued-standards/list-of-standards/ifrs-16-leases/",
  ifric1: "https://www.ifrs.org/issued-standards/list-of-standards/ifric-1-changes-in-existing-decommissioning-restoration-and-similar-liabilities/",
  ifric22: "https://www.ifrs.org/issued-standards/list-of-standards/ifric-22-foreign-currency-transactions-and-advance-consideration/",
  leaseTermDecision: "https://www.ifrs.org/projects/completed-projects/2019/lease-term-and-useful-life-of-leasehold-improvements-ifrs-16-and-ias-16/",
};

function refs(...items) {
  return items.map(([standard, paragraphs, summary, url]) => ({
    standard,
    paragraphs,
    summary,
    url,
    kasbUrl: KASB,
  }));
}

export const questions = [
  {
    id: 1,
    topic: "수익인식",
    standard: "K-IFRS 1115",
    title: "단순 항공권 중개",
    prompt: "고객은 100만원을 결제하고 여행사는 항공사에 90만원을 지급한다. 운항·결항 책임과 가격·운송조건은 항공사가 정하며 여행사는 좌석을 미리 매입하지 않는다. 여행사의 매출은?",
    options: ["100만원 총액 매출, 90만원 원가", "10만원 순액 수수료수익", "현금 100만원 전부를 계약부채", "운항 완료 전까지 아무것도 인식하지 않음"],
    correct: 1,
    answer: "10만원 순액 수수료수익",
    explanation: "여행사는 고객에게 이전되기 전에 항공운송 서비스를 통제하지 않고 항공사의 제공을 주선한다. 고객에게 현금을 직접 받았다는 사실은 본인 판단을 결정하지 않는다.",
    journal: "차) 현금·매출채권 100만원 / 대) 항공사정산채무 90만원, 항공권판매수수료수익 10만원",
    references: refs(["K-IFRS 1115 / IFRS 15", "B34–B38", "본인은 이전 전 통제한 재화·용역을 총액으로, 대리인은 주선 대가인 수수료를 순액으로 인식한다.", sources.ifrs15]),
  },
  {
    id: 2,
    topic: "수익인식",
    standard: "K-IFRS 1115",
    title: "취소 불가능한 하드블록",
    prompt: "여행사가 좌석을 70만원에 취소 불가능하게 확보하고, 팔리지 않아도 대금을 부담하며 고객 배정과 80만~120만원의 가격을 결정한다. 100만원에 판매했다면?",
    options: ["30만원 순액 수수료수익", "100만원 총액 매출과 70만원 원가", "운항사가 항공사이므로 항상 순액", "판매 전까지 우발부채만 공시"],
    correct: 1,
    answer: "100만원 총액 매출과 70만원 원가",
    explanation: "여행사는 특정 항공서비스를 받을 권리를 먼저 통제하고 미판매 위험, 고객 배정권, 가격 재량을 부담한다. 실제 운항 주체가 항공사라는 사실만으로 대리인이 되지는 않는다.",
    references: refs(["K-IFRS 1115 / IFRS 15", "B35A(a), B37", "제3자가 수행할 서비스에 대한 권리를 먼저 통제하거나 재고위험·가격 재량이 통제를 뒷받침하면 본인일 수 있다.", sources.ifrs15]),
  },
  {
    id: 3,
    topic: "수익인식",
    standard: "K-IFRS 1115",
    title: "위약금 없는 소프트블록",
    prompt: "미판매 좌석을 위약금 없이 반납하고 실제 판매분만 지급한다. 항공사가 최저가격과 최종 운송·환불 조건을 정한다. 여행사의 역할은?",
    options: ["본인—좌석을 화면에 노출했기 때문", "대리인—판매 전 권리를 실질적으로 통제하지 않음", "공동약정", "판단 없이 항상 50%만 매출"],
    correct: 1,
    answer: "대리인",
    explanation: "재고위험은 하나의 지표일 뿐이지만, 이 사례에서는 위약금 없는 반환, 판매분만 지급, 항공사의 핵심 조건 결정이 함께 여행사의 이전 전 통제 부재를 보여준다.",
    references: refs(["K-IFRS 1115 / IFRS 15", "B34–B38", "주된 이행 책임·재고위험·가격 재량은 통제 판단을 보조하는 지표이며 투표식으로 적용하지 않는다.", sources.ifrs15]),
  },
  {
    id: 4,
    topic: "수익인식",
    standard: "K-IFRS 1115",
    title: "여행사가 설계한 통합 패키지",
    prompt: "여행사가 항공·호텔·가이드를 조달해 하나의 일정으로 통합하고, 문제 시 대체 공급자를 선정하며 패키지 전체의 이행을 책임진다. 결론은?",
    options: ["외부 공급자가 수행하므로 전부 대리인", "통합된 패키지를 통제하므로 본인", "항공은 무조건 순액, 나머지는 인식 금지", "고객이 단일 가격을 내므로 계약부채만 인식"],
    correct: 1,
    answer: "통합된 패키지에 대한 본인",
    explanation: "약속한 산출물은 개별 예약의 단순 주선이 아니라 여행사가 여러 투입요소를 유의적으로 통합한 패키지다. 여행사가 결합된 서비스를 고객 이전 전에 통제한다.",
    references: refs(["K-IFRS 1115 / IFRS 15", "문단 27, 29; B35A(c)", "다른 당사자가 제공한 재화·용역을 통합해 고객에게 결합된 산출물을 제공하기 전에 통제하면 본인일 수 있다.", sources.ifrs15]),
  },
  {
    id: 5,
    topic: "수익인식",
    standard: "K-IFRS 1115",
    title: "선수금과 취소수수료",
    prompt: "7월에 10월 출발 패키지 대금 200만원을 받았다. 출발 5일 전 고객이 취소해 140만원 환불, 60만원 보유가 확정되고 잔여 수행의무는 없다. 올바른 흐름은?",
    options: ["7월 매출 200만원", "7월 계약부채 200만원 → 취소 시 환불부채 140만원·수익 60만원", "7월 환불부채 200만원 → 출발일 매출", "취소수수료는 언제나 기타포괄손익"],
    correct: 1,
    answer: "계약부채에서 환불부채와 취소수수료수익으로 전환",
    explanation: "현금 수취 시 수행의무가 남아 있으므로 계약부채다. 취소 확정으로 현금 반환 의무와 보유할 권리가 확정되면 140만원은 환불부채, 60만원은 수익이 된다.",
    journal: "수취: 차) 현금 200 / 대) 계약부채 200 · 취소: 차) 계약부채 200 / 대) 환불부채 140, 취소수수료수익 60",
    references: refs(["K-IFRS 1115 / IFRS 15", "문단 31, 55, 106; 부록 A", "수행 전 수취 대가는 계약부채이며, 환불 예상 대가는 환불부채로 표시한다.", sources.ifrs15]),
  },
  {
    id: 6,
    topic: "수익인식",
    standard: "K-IFRS 1115·1001",
    title: "3박 4일 여행의 일별 전표",
    prompt: "기간에 걸친 수행의무인 3박 4일 여행은 모든 건을 반드시 매일 안분 전표로 기록해야 할까?",
    options: ["그렇다—일별 전표가 없으면 항상 기준 위반", "아니다—원칙은 진행도 인식이나 같은 보고기간 내 중요하지 않은 차이는 실무 단순화 가능", "출발일 총액 인식만 허용", "완료일 총액 인식만 허용"],
    correct: 1,
    answer: "원칙과 전표 빈도를 구분",
    explanation: "수익은 진행도에 따라 인식하지만 K-IFRS는 전표 입력 빈도를 정하지 않는다. 짧은 서비스가 같은 보고기간에 시작·종료되고 차이가 중요하지 않다면 일별 전표 없이도 결산 재무제표가 원칙에 맞을 수 있다. 결산 경계를 넘거나 중요한 거래는 컷오프 조정한다.",
    references: refs(["K-IFRS 1115 / IFRS 15", "문단 35(a), 39–40", "고객이 수행과 동시에 효익을 얻으면 기간에 걸쳐 수익을 인식하고 진행도를 측정한다.", sources.ifrs15], ["K-IFRS 1008 / IAS 8", "문단 8", "중요하지 않은 거래에 회계정책을 적용하지 않은 효과가 중요하지 않다면 기준서 위반으로 보지 않지만, 의도적 왜곡은 허용하지 않는다.", sources.ias8]),
  },
  {
    id: 7,
    topic: "수익인식",
    standard: "K-IFRS 1115",
    title: "결산일 세 고객 분류",
    prompt: "A는 11월 여행 전 선수금 200만원, B는 취소 후 140만원 환불 예정·60만원 보유 확정, C는 200만원 여행 완료다. 결산일 잔액은?",
    options: ["계약부채 200, 환불부채 140, 총수익 260", "계약부채 340, 총수익 200", "환불부채 200, 총수익 200", "계약부채 200, 환불부채 200, 총수익 60"],
    correct: 0,
    answer: "계약부채 200만원, 환불부채 140만원, 총수익 260만원",
    explanation: "A에는 서비스 의무, B에는 현금 반환 의무와 60만원 보유 권리, C에는 완료된 수행의무가 남는다. 취소수수료도 전체 영업수익 합계에서 빠뜨리지 않는다.",
    references: refs(["K-IFRS 1115 / IFRS 15", "문단 31, 55, 106; 부록 A", "수행의무·환불의무·수익 인식 여부를 결산일 현재 의무의 성격에 따라 구분한다.", sources.ifrs15]),
  },
  {
    id: 8,
    topic: "충당부채",
    standard: "K-IFRS 1037",
    title: "세 가지 부채의 경계",
    prompt: "A: 패소 가능성 70%, 최선 추정 10억원. B: 세무추징 가능성 30%, 발생 시 5억원. C: 12월 사용료 2억원 확정, 청구서만 1월 수령. 분류는?",
    options: ["A 일반부채, B 충당부채, C 우발부채", "A 충당부채, B 우발부채 공시, C 일반 미지급부채", "A·B 모두 충당부채, C 분개 없음", "세 건 모두 주석만 공시"],
    correct: 1,
    answer: "A 충당부채, B 우발부채, C 일반 미지급부채",
    explanation: "충당부채는 현재의무, 높은 유출 가능성, 신뢰성 있는 추정을 모두 충족해야 한다. 30% 가능성은 보통 인식하지 않고 희박하지 않으면 공시한다. 청구서 미수령은 확정된 사용료 부채 인식을 막지 않는다.",
    references: refs(["K-IFRS 1037 / IAS 37", "문단 14, 23, 27–28, 36, 86", "충당부채 인식요건, 우발부채 비인식·공시, 최선의 추정치를 규정한다.", sources.ias37]),
  },
  {
    id: 9,
    topic: "충당부채",
    standard: "K-IFRS 1016·1037·해석서 2101",
    title: "해체·복구의무",
    prompt: "원전 건설 시 20년 후 복구의무 현재가치 400억원이 생기고 첫해 시간 경과 할인액 상각이 20억원이다. 올바른 처리는?",
    options: ["400억원 즉시 손실, 20억원 자산", "400억원 자산원가·충당부채, 20억원 금융비용·충당부채", "모두 주석만 공시", "400억원 기타포괄손익, 20억원 감가상각"],
    correct: 1,
    answer: "최초 복구원가는 자산화, 시간 경과분은 금융비용",
    explanation: "자산의 취득·건설 결과 발생한 최초 복구의무 추정치는 유형자산 원가와 충당부채로 인식한다. 할인액의 기간 경과는 금융원가이며, 이후 추정 변경은 해석서 2101에 따라 관련 자산과 부채를 조정한다.",
    references: refs(["K-IFRS 1016 / IAS 16", "문단 16(c)", "자산의 해체·제거 및 부지복구 추정원가는 유형자산 원가에 포함한다.", sources.ias16], ["K-IFRS 1037 / IAS 37", "문단 45, 60", "중요한 시간가치를 할인하며 할인액 상각은 금융원가다.", sources.ias37], ["K-IFRS 해석서 2101 / IFRIC 1", "문단 4–8", "기존 해체·복구충당부채 측정 변경의 자산·부채 조정을 다룬다.", sources.ifric1]),
  },
  {
    id: 10,
    topic: "리스",
    standard: "K-IFRS 1116",
    title: "사무실 리스 최초 측정",
    prompt: "5년 계약+3년 연장선택권, 맞춤 인테리어 3억원과 높은 이전비용, 연 1억원 후급·할인율 5%, 매출 1% 추가 지급이다. 가장 타당한 처리는?",
    options: ["선택권이 있으니 무조건 8억원 부채", "행사가 상당히 확실하면 8년; 고정료 현재가치 약 6.46억원; 매출연동액은 발생기 비용", "5년만 인식하고 인테리어를 리스부채에 포함", "모든 임차료를 매년 단일 리스비용"],
    correct: 1,
    answer: "경제적 유인으로 리스기간을 판단하고 고정료를 현재가치 측정",
    explanation: "연장선택권은 행사가 상당히 확실할 때 포함한다. 맞춤 인테리어와 이전비용은 경제적 유인이다. 매출연동 변동리스료는 지수·이율 연동이 아니므로 최초 부채에서 제외한다. 인테리어는 일반적으로 별도 유형자산이다.",
    references: refs(["K-IFRS 1116 / IFRS 16", "문단 18–21, 24, 26–27, 38(b); B37–B40", "리스기간, 사용권자산 원가, 리스료 현재가치, 지수·이율 외 변동리스료를 규정한다.", sources.ifrs16], ["K-IFRS 1016 / IAS 16", "문단 7, 16", "별도 인테리어가 유형자산 인식요건을 충족하면 별도 자산으로 회계처리한다.", sources.ias16], ["IFRS 해석위원회 안건결정", "2019.11 Lease Term and Useful Life of Leasehold Improvements", "리스개량의 경제적 효익과 포기 비용이 연장·종료 선택권 판단에서 경제적 불이익을 만드는지 검토한다.", sources.leaseTermDecision]),
  },
  {
    id: 11,
    topic: "리스",
    standard: "K-IFRS 1116",
    title: "연장선택권 판단 변경",
    prompt: "8년으로 보던 리스가 재택근무 확정으로 최초 5년 만료 시 이전할 것이 상당히 확실해졌다. 감가상각기간만 줄이면 될까?",
    options: ["그렇다—자산만 줄이면 충분", "아니다—리스부채를 수정 할인율로 재측정하고 사용권자산을 조정", "리스부채 전액을 즉시 이익", "아무 조정 없이 주석만 공시"],
    correct: 1,
    answer: "리스부채 재측정과 사용권자산 조정이 먼저",
    explanation: "리스기간 변경은 남은 지급의무 자체를 바꾸므로 감가상각기간만 줄일 수 없다. 수정 할인율로 리스부채를 재측정하고 사용권자산을 조정한 뒤 수정 잔여기간에 감가상각한다.",
    references: refs(["K-IFRS 1116 / IFRS 16", "문단 20–21, 39–43", "통제 가능한 유의적 사건이 선택권 판단을 바꾸면 리스기간을 재평가하고 수정 할인율로 부채를 재측정한다.", sources.ifrs16], ["IFRS 해석위원회 안건결정", "2019.11 Lease Term and Useful Life of Leasehold Improvements", "리스개량과 이전·포기 비용은 선택권 행사의 경제적 유인을 평가할 때 관련될 수 있다.", sources.leaseTermDecision]),
  },
  {
    id: 12,
    topic: "리스",
    standard: "K-IFRS 1116",
    title: "사무실 절반 반환",
    prompt: "기존 사무실 절반을 즉시 반환하고 임차료도 50%로 줄였다. 회계처리는?",
    options: ["감가상각만 절반", "일부 종료로 자산·부채를 비례 제거하고 차이는 손익, 남은 리스를 재측정", "임차료 감소 전액을 즉시 수익", "별도 리스 추가"],
    correct: 1,
    answer: "리스 범위 감소에 따른 일부 종료",
    explanation: "사용권 범위가 감소했으므로 반환 부분의 사용권자산과 리스부채 장부금액을 제거하고 차이를 손익으로 인식한다. 이후 남은 조건을 수정 할인율로 재측정한다.",
    references: refs(["K-IFRS 1116 / IFRS 16", "문단 45–46(a)", "리스 범위를 감소시키는 계약변경은 사용권자산 장부금액을 줄여 일부·전부 종료를 반영하고 손익을 인식한다.", sources.ifrs16]),
  },
  {
    id: 13,
    topic: "리스",
    standard: "K-IFRS 1116",
    title: "면적·기간은 그대로, 임차료만 인하",
    prompt: "사용 면적과 기간은 그대로지만 새 협상으로 남은 임차료가 20% 낮아졌다. 회계처리는?",
    options: ["일부 종료손익", "수정 할인율로 리스부채를 재측정하고 사용권자산 조정", "별도 리스", "재무제표 조정 없음"],
    correct: 1,
    answer: "범위 감소 없는 계약변경 재측정",
    explanation: "사용권 일부가 소멸하지 않았으므로 일부 종료가 아니다. 변경된 대가를 수정 할인율로 재측정하고 차이는 사용권자산에 조정한다.",
    references: refs(["K-IFRS 1116 / IFRS 16", "문단 45, 46(b)", "별도 리스가 아니고 범위 감소도 아닌 계약변경은 수정 할인율로 부채를 재측정하고 사용권자산을 조정한다.", sources.ifrs16]),
  },
  {
    id: 14,
    topic: "리스",
    standard: "K-IFRS 1116",
    title: "시장가격으로 옆 사무실 추가",
    prompt: "독립적으로 사용할 수 있는 옆 사무실을 해당 공간의 시장가격으로 추가 임차한다. 회계처리는?",
    options: ["기존 리스 일부 종료", "별도의 새로운 리스", "기존 리스의 손익 재측정", "우발리스로 주석만 공시"],
    correct: 1,
    answer: "별도 리스",
    explanation: "추가 사용권으로 범위가 증가하고 추가 대가가 개별가격에 상응하므로 기존 리스와 분리해 새로운 사용권자산과 리스부채를 인식한다.",
    references: refs(["K-IFRS 1116 / IFRS 16", "문단 44", "사용권 추가로 범위가 증가하고 대가가 개별가격에 상응하면 별도 리스로 회계처리한다.", sources.ifrs16]),
  },
  {
    id: 15,
    topic: "금융상품",
    standard: "K-IFRS 1109·1010",
    title: "매출채권 기대신용손실",
    prompt: "5억원 매출채권이 120일 연체됐다. 전액 회수 60%, 50% 회수 30%, 전액 미회수 10%다. 결산 후 승인 전 회생절차 신청이 있었다. 올바른 결론은?",
    options: ["과거 회수했으므로 충당금 0", "기대손실 1.25억원·순채권 3.75억원, 회생정보로 결산 추정 재검토", "기대손실 3.75억원", "회생신청은 언제나 다음 연도만 반영"],
    correct: 1,
    answer: "확률가중 기대신용손실 1.25억원",
    explanation: "확률가중 기대회수액은 3.75억원이고 손실은 1.25억원이다. 결산일에 이미 장기연체와 자금난이 있었다면 승인 전 회생신청은 기존 상태를 확인하는 수정후사건일 수 있어 추정치를 갱신한다.",
    references: refs(["K-IFRS 1109 / IFRS 9", "문단 5.5.8, 5.5.15, 5.5.17", "매출채권의 전체기간 기대신용손실과 확률가중·합리적 전망을 반영한다.", sources.ifrs9], ["K-IFRS 1010 / IAS 10", "문단 8, 9(b)(i)", "보고기간 후 고객 파산은 대개 보고기간 말 신용손상을 확인해 손실충당금 조정을 요구한다.", sources.ias10]),
  },
  {
    id: 16,
    topic: "금융상품",
    standard: "K-IFRS 1010",
    title: "결산 후 처음 발생한 화재",
    prompt: "결산일까지 정상 결제하고 재무상태가 양호하던 고객이 다음 해 1월 대형 화재로 처음 지급불능이 됐다. 결산연도 처리는?",
    options: ["손실충당금 즉시 증액", "금액은 수정하지 않고 중요하면 비수정후사건 주석 공시", "전액 대손상각", "기타포괄손익"],
    correct: 1,
    answer: "비수정후사건",
    explanation: "화재는 결산일 현재 상태를 확인하는 사건이 아니라 결산일 후 새 상태를 만든다. 금액은 수정하지 않고 중요하면 성격과 추정 재무영향을 공시한다.",
    references: refs(["K-IFRS 1010 / IAS 10", "문단 3, 21–22(b)", "보고기간 후 화재에 의한 주요 생산시설 파괴는 비수정후사건의 공식 예시다.", sources.ias10]),
  },
  {
    id: 17,
    topic: "외화",
    standard: "K-IFRS 1021",
    title: "외화 미지급금",
    prompt: "미화 100만 달러 호텔 미지급금의 거래일 환율 1,300원, 결산일 1,400원, 지급일 1,350원이다. 올바른 처리는?",
    options: ["최초 13억원 유지, 환차손익 없음", "결산 14억원·환산손실 1억원, 지급 시 외환차익 0.5억원", "결산 14억원을 호텔원가에 추가", "모든 차이를 기타포괄손익"],
    correct: 1,
    answer: "마감환율 재환산 후 당기손익",
    explanation: "외화 미지급금은 화폐성 부채이므로 결산일 마감환율로 재환산한다. 14억원 장부부채를 13.5억원에 결제하면 5천만원 이익이 발생한다.",
    references: refs(["K-IFRS 1021 / IAS 21", "문단 21, 23(a), 28", "외화거래는 거래일 현물환율로 최초 인식하고 화폐성 항목은 마감환율로 환산하며 차이는 원칙적으로 손익이다.", sources.ias21]),
  },
  {
    id: 18,
    topic: "외화",
    standard: "K-IFRS 1021·해석서 2122",
    title: "환불 불가능 외화 선급금",
    prompt: "미화 100만 달러를 환율 1,300원에 환불 불가능하게 선지급했고 다음 해 호텔 서비스를 받는다. 결산일 환율은 1,400원이다. 선급금은?",
    options: ["14억원으로 재환산하고 이익", "13억원 유지—서비스를 받을 비화폐성 권리", "전액 환불부채", "환율차이를 기타포괄손익"],
    correct: 1,
    answer: "13억원 유지",
    explanation: "선급금은 외화를 돌려받을 권리가 아니라 서비스를 받을 비화폐성 권리다. 역사적 원가 비화폐성 항목은 거래일 환율을 유지하며, 해석서 2122는 선급대가 인식일을 거래일로 본다.",
    references: refs(["K-IFRS 1021 / IAS 21", "문단 8, 16, 23(b)", "역사적 원가로 측정하는 외화 비화폐성 항목은 거래일 환율로 환산한다.", sources.ias21], ["K-IFRS 해석서 2122 / IFRIC 22", "문단 8–9", "선급·선수 대가와 관련된 비화폐성 자산·부채를 최초 인식한 날이 거래일이다.", sources.ifric22]),
  },
  {
    id: 19,
    topic: "외화",
    standard: "K-IFRS 1021",
    title: "선급금 70%·미지급금 30%",
    prompt: "70만 달러는 환불 불가능 선급금, 30만 달러는 이미 무조건적 지급의무인 미지급금이다. 최초 환율 1,300원, 결산환율 1,400원이다. 결산 처리는?",
    options: ["둘 다 재환산", "둘 다 역사적 환율", "선급금 9.1억원 유지, 미지급금 4.2억원으로 재환산·손실 0.3억원", "미지급금 인식 취소"],
    correct: 2,
    answer: "비화폐성 선급금은 유지, 화폐성 미지급금만 재환산",
    explanation: "결제 여부가 아니라 받을 권리·지급할 의무의 성격이 기준이다. 다만 서비스 제공 전이고 30만 달러 의무가 아직 무조건적이지 않다면 먼저 부채 인식 여부부터 검토한다.",
    references: refs(["K-IFRS 1021 / IAS 21", "문단 8, 16, 23", "화폐성 항목은 확정·결정 가능한 화폐 단위를 수취·지급할 권리·의무이며 마감환율로 환산한다.", sources.ias21]),
  },
  {
    id: 20,
    topic: "위험회피",
    standard: "K-IFRS 1109·1032",
    title: "문서화하지 않은 선도계약",
    prompt: "외화 미지급금을 경제적으로 위험회피하려고 선도계약을 체결했지만 지정·문서화하지 않았다. 결산일 선도계약은 8천만원 자산이다. 처리는?",
    options: ["실제 목적이므로 자동으로 OCI", "파생상품자산 8천만원과 당기손익 평가이익; 미지급금과는 원칙적으로 총액 표시", "결제 전이므로 인식 금지", "선도계약을 미지급금 원가에 가산"],
    correct: 1,
    answer: "기본 공정가치-당기손익 회계",
    explanation: "경제적 위험회피와 위험회피회계 적격성은 다르다. 공식 지정·문서화 등 요건이 없으면 파생상품 공정가치 변동은 당기손익이다. 서로 다른 상대방의 자산·부채는 상계요건을 충족하지 않으면 총액 표시한다.",
    references: refs(["K-IFRS 1109 / IFRS 9", "문단 4.1.4, 4.2.1(a), 5.7.1, 6.4.1", "기본적으로 파생상품은 공정가치-당기손익이며 위험회피회계는 지정·문서화와 적격요건을 요구한다.", sources.ifrs9], ["K-IFRS 1032 / IAS 32", "문단 42", "법적으로 집행 가능한 상계권과 순액결제 의도가 모두 있어야 금융자산·부채를 상계한다.", sources.ias32]),
  },
  {
    id: 21,
    topic: "위험회피",
    standard: "K-IFRS 1109",
    title: "적격 현금흐름위험회피",
    prompt: "발생 가능성이 매우 높은 외화 매입을 선도계약으로 적격 지정했다. 평가이익 8천만원은 전액 효과적이고 이후 비금융자산을 인식한다. 처리는?",
    options: ["평가이익 전액 당기손익", "파생상품자산·OCI, 이후 누적이익을 비금융자산 원가에 기초조정", "파생상품을 인식하지 않음", "OCI에 영구히 유지"],
    correct: 1,
    answer: "효과적 부분 OCI 후 비금융자산 원가 기초조정",
    explanation: "현금흐름위험회피의 효과적인 부분은 기타포괄손익에 누적한다. 예상 거래로 비금융자산이 생기면 누적액을 즉시 손익으로 재분류하지 않고 자산 최초 원가에 포함한다.",
    references: refs(["K-IFRS 1109 / IFRS 9", "문단 6.5.11(c), 6.5.11(d)(i)", "효과적 부분은 현금흐름위험회피적립금에 누적하고 비금융자산·부채 인식 시 장부금액에 직접 포함한다.", sources.ifrs9]),
  },
  {
    id: 22,
    topic: "위험회피",
    standard: "K-IFRS 1109",
    title: "예상 거래의 연기와 취소",
    prompt: "현금흐름위험회피 대상 매입이 A) 3개월 연기됐지만 여전히 발생 가능성이 매우 높음, B) 협상 종료로 더 이상 발생하지 않을 것으로 예상된다. 누적 OCI 처리는?",
    options: ["A·B 모두 즉시 손익", "A 유지, B 즉시 당기손익 재분류", "A 즉시 손익, B 영구 OCI", "A·B 모두 자산 원가"],
    correct: 1,
    answer: "A는 유지, B는 즉시 손익",
    explanation: "거래가 여전히 발생할 것으로 예상되면 기존 누적액은 적립금에 남는다. 더 이상 발생하지 않을 것으로 예상되면 대응할 미래 거래가 없으므로 누적액을 즉시 손익으로 재분류한다.",
    references: refs(["K-IFRS 1109 / IFRS 9", "문단 6.5.12", "예상 거래가 더 이상 발생할 것으로 예상되지 않으면 누적 현금흐름위험회피적립금을 즉시 손익으로 재분류한다.", sources.ifrs9]),
  },
];

export const topics = [...new Set(questions.map((question) => question.topic))];
